author: qrearded
name: GamemodeUI
version: 1.0.0
main: qrearded\GamemodeUI\main
api: 3.21.0
softdepend:
- PurePerms

commands: 
   gamemodeui:
    description: Choose your game mode.
   gmui:
       description: Choose your game mode.
