author: qrearded
name: GamemodeUI
version: 1.0.1
main: qrearded\GamemodeUI\main
api: 3.25.1
softdepend:
- PurePerms

commands: 
   gamemodeui:
    description: Choose your game mode.
   gmui:
       description: Choose your game mode.
