author: qrearded
name: GamemodeUI
version: 0.2.0
main: qrearded\GamemodeUI\main
api: 3.15.0

commands: 
   gamemodeui:
    description: Choose your game mode.
   gmui:
       description: Choose your game mode.
